#!/bin/bash

# This task needs to left as it is
# This is for external plugins and programs to query the available tasks
function __show_tasks() {
        compgen -A function | grep -v "^_"
}
# This needs also be left as it is
# It's used to check for function existence
function __fn_exists() { test x"$(type -t "$1")" = xfunction; }

# Helper functions start with _ and are invisible to bash auto completion.
function _get_random_number {
        local min=$1
        local max=$2
        echo $(( ( RANDOM % max )  + min ))
}

# Simple logger helper function
function _logger {
        local _date
        _date=$(date --rfc-3339=ns)
        echo -ne "$_date\\t$*\\n"
}

function generate_javascript_vars_from_html {
        local js_var_name=$1
        local html_filepath=$2
        local html_contents
        local js_var_contents
        html_contents=$(cat "$html_filepath")
        js_var_contents=$(jshon -s "$html_contents" 2>/dev/null)
        echo "var $js_var_name=$js_var_contents;"
}

# This is just an example
function build {
        local rand
        rand=$(_get_random_number 1 10)
        local i=0
        echo
        echo "Build $1"
        while [ "$i" -lt "$rand" ]; do
                sleep 1
                echo  " Computing $1 ..."
                ((i++))
        done
        echo "Finished $1"
        echo
}

# Watching for changes and then rebuild automatically
# Easy as pie!
function watch {
        local watchdir="./src/"
        _logger "Watcher started"
        inotifywait -m -r -e close_write --format '%w%f' "${watchdir}" | \
        while read -r _; do
                _logger "Build triggered"
                Task build
                _logger "Build finished"
        done
}

## Deploy to a remove server using rsync is easy as fuck!
function deploy {
        local username
        local hostname
        local upload_dir
        username="$(jq -r .deployment.username < ./config.json)"
        hostname="$(jq -r .deployment.hostname < ./config.json)"
        upload_dir="$(jq -r .deployment.upload_dir < ./config.json)"
        rsync -av --no-o --no-g ./dist/ "$username"@"$hostname":"$upload_dir"
}

## Watch the src dir for changes and then auto-build and auto-deploy
function auto-deploy {
        local watchdir="./src/"
        _logger "Auto-Deploy started"
        inotifywait -m -r -e close_write --format '%w%f' "${watchdir}" | \
        while read -r _; do
                _logger "Build triggered"
                Task build
                _logger "Build finished"
                _logger "Deployment triggered"
                deploy
                _logger "Deployment finished"
        done
}

# Parallelisation - run multiple tasks in parallel.
function build-all {
        # Run these Tasks in parallel
        build android & build iphone & build ipad & build web &
        # .. and wait until every Task has finished
        wait
}

# Another example, but it's always a good practice to have a help function
function help {
        echo "$0 <task> <args>"
        echo "Tasks:"
        __show_tasks | cat -n
}

# This is a wrapper for what should be executed, when no args are passed to the
# Taskfile
function default {
        __show_tasks
}

if [[ -n $1 ]]; then
        __fn_exists "$1" && "$@" || echo "Task \"$1\" does not exist." && exit 1;
else
        default
fi

